# Generated by Django 3.1.5 on 2023-08-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230822_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='slug',
        ),
    ]
