# Generated by Django 3.1.5 on 2023-08-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_logo', models.FileField(upload_to='core/brand-logo')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Marka nomreleri',
                'verbose_name_plural': 'Marka nomreleri',
            },
        ),
        migrations.CreateModel(
            name='CampaignText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Kampaniya məlumatları',
                'verbose_name_plural': 'Kampaniya məlumatları',
            },
        ),
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='core/logo')),
                ('favicon', models.FileField(upload_to='core/favicon')),
            ],
            options={
                'verbose_name': 'Əsas məlumatlar',
                'verbose_name_plural': 'Əsas məlumatlar',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='core/slider')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('product', models.ManyToManyField(blank=True, null=True, related_name='sliders', to='product.Product')),
            ],
            options={
                'verbose_name': 'Slayder',
                'verbose_name_plural': 'Slayder',
            },
        ),
    ]
