# Generated by Django 3.1.5 on 2023-08-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slider_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='product',
            new_name='products',
        ),
    ]
