# Generated by Django 3.1.5 on 2023-08-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230822_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntext',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
