# This is a basic workflow to help you get started with Actions

name: CI/CD Django, Postgres, DigitalOcean

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    services:
      postgres_main:
        image: postgres:9.6
        env:
          POSTGRES_USER: user_avtobaza
          POSTGRES_PASSWORD: lAg24124askldm34%%ad@4rmsj*jan_3413%$v%cu1*g
          POSTGRES_DB: avtobaza_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version:  3.11
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run Tests
        env:
          DEBUG: "0"
          DJANGO_SECRET_KEY: CI_CD_TEST_KEY
          POSTGRES_USER: user_avtobaza
          POSTGRES_PASSWORD: lAg24124askldm34%%ad@4rmsj*jan_3413%$v%cu1*g
          POSTGRES_DB: avtobaza_db
          POSTGRES_PORT: 5432
        run: |
          python manage.py test
      - name: Push Main branch into Production
        uses: k4rimdev/action-branch-to-branch@main
        with:
          dest_branch: production-3
          source_branch: main
          commit_message: "Release production version"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Run DOCTL Command
        run: |
          doctl apps update ${{ secrets.DO_APP_ID }} --spec .do/app.yml
          